mgguild/msw-website

css/styles.css
index.html
js/scripts.js

This resolves the following issues:
Resolves issue #46 Fix team alignments
35853ec77620c2c22602dd170b629413d96515a3
Resolves issue #47 Fix iPad mini and tablet view navbar logo
c5713c1cb42bc2aa53698b543c099694079bc6b5

Alignment issues

---

css/carousel.css
css/scroll.css
css/styles.css
index.html

This resolves the following Issues:
Resolves issue #41  NFT Characters UI 
9f1a94286ea2f23f840b2b1bfe22374f93c5b133
ed789c180e6189930c82a72cdbfbadebd73243e1
For mobile view:
For tablet view:
For desktop view:
Resolves issue #50 Story & Narrative section update
90a6d7b09d8eb24b9a5585aeb4bfacf46db8e76b
For desktop view:
For tablet view:
For mobile view:

Update Sections UI

---

css/styles.css
index.html

Resolves issue #68 
53640ecd89e804c47ca84f7015f260c89e486fea

Add medium link in social media footer 

---

css/styles.css
index.html

This resolves the following issue:
Resolves issue #100 UI update and fixes Sept 9 2022 e92ebe8675a6dce72b1b9a523d0308789fd691ae
Remove GIF, Center the paragraph and enlarge the font.
Make the Font Bigger, And align the bullets straight like the red line, move this titles to the left.
Fill this in and use the scroll from next page:
Drop down color, smooth curve edges and remove the Frequently asked question below FAQs. 
Resolves issue #101 make text bigger in footer 7136594e943b8bf84af6b99c9d29b245ef696e1e
EDIT: 
CHANGED: c079d7eeb9b669cf23e46c4b4b27087a1e4c58f3
Placeholder adjust to the right side
Extra white space, deleted
EDIT: 
Changes email placeholder on desktop view from left to center :  9834f9e3fc86f50cf4ed72558c251001f9696704  abedc3695bfb9c919b364bfa9c144718139c8bd7
Resolves …

UI fixes and update

---

css/styles.css
index.html

Reverts mgguild/msw-website#102

Revert "UI fixes and update"

---

css/styles.css
index.html

Resolves issue #106
d7b5b1607dc8af2e279d2e9d8a07b6cc7a0e16f7

Add contents to FAQs sections 

---

css/styles.css
index.html

This resolves issue #112 Added open play beta link 2ff3c2c8f5d815a78713a962e8ca62d154b80faf

Add link beta

---

css/styles.css
index.html
js/scripts.js

This resolves issue #116 Add minting button 736bdc4175af514b31665af9bfa91f2b2f4dcfb2

Add minting button

---

index.html

Change digglers to Diggers resolves issue #120 60bc1da59b09d66b3a28d393007ce6933df3c70f

Change digglers to Diggers 

---

css/styles.css
index.html
js/scripts.js

This resolve issue #123 Add Youtube Link  a0205154c0eddb2a434c40c6f5d15510192af38b 292230e8882321b68822c833e160d9253a141f16
On Web:
On mobile:

Add Youtube link

---

index.html

This resolve issue #125 Remove Yandro on Team Section 76ff5f385a9cb33f33aa3dfea77f814f40e4e2df ae6a3f818ff8f3025f5ddd430eb1b96a7f8a8c8e
On Mobile: 
On Web:
On Tablet:

Remove content strategist

---

js/scripts.js

This resolves issue #115 Section tabs does not work in mobile view  3572534bae56452698bf6bbeb1c97d1704f92fe1

Fix section tabs in mobile view 

---

css/carousel.css
css/scroll.css
css/styles.css
index.html
js/scripts.js

This resolve issue #128 Gameplay Section Bug e0ec604d15d0b429a03f4bac103abba114b86b9f
Remove effects in carousel to fix bug in Gameplay Section

Gameplay Section Bug 

---

css/scroll.css
css/styles.css
index.html

This resolves issue #137 FAQ's Section Update 426c9d2813c066e7359f29d2ef07cf84ae9a2d81

Update faqs minting date

---

css/scroll.css
css/styles.css
index.html

This resolves issue #138 Fix name placement on mobile cc221bf1d4fdec5eb7934ac472a174b976b5b79a

Fix name placement of one of ones in mobile

---

css/scroll.css
index.html

This resolves issue #141 Add Gitbook on website 834276a73c51c934eae85bb740e97cf9b7d58960
Additional Fix: beb6f8d6bf9c9c19de39817f174c966e8e08bb6

Update msw socials

---

css/styles.css
index.html

This resolves issue #150 Reveal Archer on 1of1's Section 32c9ea768a3e0207493a11de12a5aa57dc3c8643

Reveal Archer on one of ones 

---

index.html

This resolves issue #158 Remove unnecessary spaces 54f1d724cf86b64442b6645e378a82350b6391b9

Remove unnecessary spaces 

---

css/styles.css
index.html

This resolves the following issues:
Resolves Issue #162 Replace FAQ's contents 37209b203b4c5bec6fc45bd6bdbb8b2c90fa1e6c
Resolves Issue #163 Replace 1of 1s with Whitelist Checker on Navbar 2f8fab279d0533c15a49817605fd123cdd8f7306
Resolves Issue #164 Replace Game Description f639c0d8ea60d512d3f26b78029daac13afdaa24

Add whitelist checker 

---

css/styles.css
index.html

This resolves the following issue:
Resolves issue #167 Make the 'whitelist checker' a button a601ddd4a4837e6fa92634db3d52fa02e8837795 d79360f43ab09f06dedf78d299ede961c6219395
Resolves issue #166 Add Space in between on about page paragraph 5b3585831b1b969d988ecb70345d8985008fce11

Add whitelist button

---

index.html

This resolves issue #179 Replace FAQs 8705fdbeaff36764e63b09d914dba5b05c34ac4b
Additional: Make button in view collection open to a new tab bb54d6e7b0dddab3c9e4597097ad1633b282470f

Update FAQs for April

---

index.html

This resolves issue #181 Update FB Link 2500ea7660a3ad17adbe8304fec01d319f9ff6be

Update fb link 

---

css/styles.css
index.html
js/scripts.js

This resolves issue #183 Update Game Link 591be934b629efc23c7f88a933f64ffdcf8bc205

Update game link 

---

index.html

Update a new game link resolves issue #183 04cc9b11ed459c93ca0b786f6d63de7c5766370f

Update new game link 

---

css/scroll.css
css/styles.css
index.html

This resolves issue #223 Selecting Dark Knight causes the containers to move 073e0cf55f883b2fe916bd2f8fe1c095453b4107

Added dark knight utility stats 

---

css/styles.css
privacy_policy.html
terms_and_condition.html

This resolves issue #248 Terms and Condition Fix e491be1d79c921f067d1e4839f40edb3e59cbee8

Fix terms & condition 

---

index.html

Remove countdown timer issue #260 ce0c1daa81f2cec0a7e163ef3c3973721cf52a70

Remove countdown timer

---

css/styles.css

Replace black and white background with colored on mobile #260 b8146b93439dd13dbe2ff99238cc379d2afce30f

Replace black and white background with colored on mobile

---

src/App.tsx
src/Components/Data/NavItems.ts
src/Components/Pages/About.tsx
src/Components/Pages/FAQ.tsx
src/Components/Pages/Gallery.tsx
src/Components/Pages/Gameplay.tsx
src/Components/Pages/Lore.tsx
src/Components/Pages/NFTs.tsx
src/Components/Pages/Team.tsx

Fix navbutton anchoring by changing scrollto function in gsap

Fix anchoring

---

src/App.css
src/Components/Pages/Lore.tsx
src/Components/Pages/NFTs.tsx
src/Components/Pages/Partners.tsx

This resolves the following issues:
Issue #270 Fix NFT Character Section 28583dd02d6a0556c0578caaa454ef5cb10346a0
Issue #274 Next arrow on Lore 814784cb325f302b93588cc98506f16dfc9be8e9
Issue #277 Apple Air Devices Fix f15d71f65ddda7f25963e88138965b384117d82e

Update React-website fixes

---

src/App.css
src/Components/Pages/Lore.tsx
src/Components/Pages/NFTs.tsx
src/Components/Pages/Partners.tsx

Reverts mgguild/msw-website#279

Revert "Update React-website fixes"

---

package-lock.json
package.json
src/Components/Pages/Lore.tsx
src/Components/Pages/NFTs.tsx
yarn.lock

This resolves issue #281 Mobile view fix e7e5bf15ebcc14fc4a8419e029116c4ccd883fc8 a42fc318e5a2020a37bd63512eb7cf35e51a1452
Dimensions 390 x 844
Lore:
Nft Character Section with visible scroll

Mobile view fix

---

src/Components/Modals/PrivPolTermsCond.tsx
src/Components/Modals/index.ts
src/Components/Pages/Footer.tsx

Closes [#285](https://github.com/mgguild/msw-website/issues/285)

Fix missing privaciy policy & terms & conditions

---

src/Components/Modals/PrivPolTermsCond.tsx
src/Components/Modals/index.ts
src/Components/Pages/Footer.tsx
src/Components/Pages/Team.tsx

Fix teams portrait scaling

---

src/Components/Pages/About.tsx
src/Components/Pages/FAQ.tsx
src/Components/Pages/Footer.tsx
src/Components/Pages/Gallery.tsx
src/Components/Pages/Gameplay.tsx
src/Components/Pages/Home.tsx
src/Components/Pages/Lore.tsx
src/Components/Pages/NFTs.tsx
src/Components/Pages/Partners.tsx
src/Components/Pages/Team.tsx
src/Components/Styled/index.tsx

Issue #295 Add trailer on Website
Issue #299 Chang copyright year to 2024
Issue #291 Make Section title larger on mobile view

Update mobile issues

---

src/index.tsx

- Use hash routing instead of browser routing issues with github pages

use hashrouter

---

package.json
src/Components/Modals/PrivPolTermsCond.tsx
src/Components/Modals/UserDashboard.tsx
src/Components/Pages/AccountDelete/AccountDelete.tsx
src/Components/Pages/Main/Sections/About.tsx
src/Components/Pages/Main/Sections/Footer.tsx
src/Components/Pages/Main/Sections/Home.tsx
src/Components/Pages/Main/Sections/Lore.tsx
src/Components/Pages/Main/Sections/NFTs.tsx
src/Components/Pages/Main/Sections/Team.tsx
src/index.tsx
yarn.lock

- Added thirdweb react sdk
- Converted userdashboard react component states and hooks to thirdweb wallet connect components
- Added perttier script in package.json

Convert wallet connect to thirdweb components

---

src/App.css
src/App.tsx
src/Components/Data/DiggerParts.ts
src/Components/Marketplace/views/MarketplaceV2/Views/NFTPage/index.tsx
src/Components/Marketplace/views/MarketplaceV2/components/Card/Display.tsx
src/Components/Marketplace/views/MarketplaceV2/components/Foundation/Iconloader/index.tsx
src/Components/Marketplace/views/MarketplaceV2/components/Socials/index.tsx
src/Components/Marketplace/views/MarketplaceV2/constants/config.d.ts
src/Components/Marketplace/views/MarketplaceV2/constants/config.ts
src/Components/Modals/LoginRegister.tsx
src/Components/Modals/ModalWarn.tsx
src/Components/Modals/UserDashboard.tsx
src/Components/Modals/index.ts
src/Components/Pages/AccountVerfied/AccountVerified.tsx
src/Components/Pages/AccountVerfied/index.tsx
src/Components/Pages/Main/Sections/Footer.tsx

Issues fixed
- Fixed playfab email sending error
- Added account recovery modal section, Closes #336 
- Updated xtwitter logo in main & marketplace components, Closes #341 
- Changed NFT image img display adaptability, Closes #345 
- Added back button to /marketplace in NFTinfo page component, #346 
- Make modal background opaque and hide profile display when not logged in in user page component, Closes #348 
- Added back button to persistent modal to marketplace page, Closes #349 #330 
@justinbalaguer fixes:
Closes #329 #331 #332 #333 #334 #335 #337 #338 #339 #340 #342 #344

Fixed raised issues

---

src/Components/Marketplace/contexts/MarketplaceDataContext.tsx
src/Components/Marketplace/hooks/useSubgraph.ts
src/Components/Marketplace/views/MarketplaceV2/Views/Market/Nftlist.tsx
src/Components/Marketplace/views/MarketplaceV2/Views/NFTPage/index.tsx
src/Components/Marketplace/views/MarketplaceV2/Views/User/NftCollection.tsx
src/Components/Marketplace/views/MarketplaceV2/components/Card/index.tsx

- Fix Dark knight bug on individual nft page closes #369 
- Cancel listing button now appears to owned users in listing page when wallet is connectes, closes #367 
- Add toast prompt to successful unlisting, closes #365 
- Add word "to" in cancel listing modal, closes #364

Fix issues
